### ISSUE TITLE
редактор/просмотрщик docflow:возможность перехода к подпроцессу

### ISSUE THREAD

**Issue by itiu** [karpovr/veda#13]
для редактора и для просмотрищика требуется возможность выполнения перехода к вложенному маршруту, задача с вложенным маршрутом ничем не отличается от простых задач.

для редактора сети ориентироватся на поле:
v-wf:subNet
	rdf:type rdf:Property ;
	rdfs:isDefinedBy v-wf: ;
	rdfs:label "subnet"@en ;
	rdfs:label "подсеть"@ru ;
	rdfs:domain v-wf:Task ;
	rdfs:range v-wf:Net ;
.

для просмотрщика процесса ориентироватся на поле:
v-wf:isProcess
	rdf:type owl:ObjectProperty ;
	rdfs:isDefinedBy v-wf: ;
	rdfs:label "Запущен процесс"@ru ;
	rdfs:label "Started process"@en ;
	rdfs:domain v-wf:StartForm ;
	rdfs:domain v-wf:WorkOrder ;
	rdfs:range v-wf:Process ;
.

**Comment by xupyprmv** [comment]
Возможность провалиться в подмаршрут в редакторе маршрута осуществляется по нажатию лупы.

Возможность просмотреть подпроцессы осуществляется через правую шаблыжку.
