### ISSUE TITLE
редактор docflow:нужен компактный шаблон для отображения и редактирования свойств элементов сети

### ISSUE THREAD

**Issue by itiu** [karpovr/veda#15]
картинка для примера, как это делают хорошие люди:
![screenshot - 06092015 - 05 00 31 pm](https://cloud.githubusercontent.com/assets/64830/8059509/0fb454ba-0ec9-11e5-808f-3f52453d8cfa.png)

**Comment by xupyprmv** [comment]
Сделаны шаблоны для Net, Task, Condition и Flow.
