### ISSUE TITLE
Поправить выгрузку в ttl

### ISSUE THREAD

**Issue by lexiqq** [karpovr/veda#19]
При выгрузке id экземпляров сопровождаются угловыми скобками. Надо убрать скобки, спереди поставить ":"

**Comment by xupyprmv** [comment]
https://github.com/karpovr/veda/commit/75a349c4e130d5246e2329693e4718fc5e1d5925
https://github.com/karpovr/veda/commit/b4c5e83b0587e3f83b8005fde7488c351aec6ed0
