### ISSUE TITLE
протянуть в модель поиска возможность указывать дополнительные параметры

### ISSUE THREAD

**Issue by itiu** [karpovr/veda#2]
@path("query") @method(HTTPMethod.GET)
string[] query(string ticket, string query, string sort = null, string databases = null, bool reopen = false);

**Comment by karpovr** [comment]
commitID: 0e28eeed8896f7c3e0b7eb5bfa85f289791ad21e
2 params added to search method in SearchModel && v-fs:SearchModel.
Parameters are:
1) databases - names of server-side xapian databases to execute query against
2) reopen - reopen xapian database
