### ISSUE TITLE
редактор docflow: некорректное поведние элемента flow

### ISSUE THREAD

**Issue by itiu** [karpovr/veda#5]
некорректное поведние элемента flow:
- стрелки часто слипаются в одну на входе или выходе, при наведении курсора обратно разлипаются
- меняются местами, при наведении курсора обратно встают на свои места

**Comment by xupyprmv** [comment]
Это поведение библиотеки jsPlumb, которую мы используем. Я подумаю что можно сделать с этой проблемой. По идее стрелками мы не управляем - они не являются отдельной сущностью с константами для графического отображения (координаты узловых точек, кривизна) - мы отдали всё на откуп jsPlumb`у.

**Comment by xupyprmv** [comment]
Изменения внесены. Теперь позиции (якоря) для входящих / исходящих стрелочек строго фиксированы (чередуются по левой/верхней/правой границе). Соединение производится всегда между ближайшем исходящим->входящим якорем.
