### ISSUE TITLE
просмотрщик docflow: показ переменных

### ISSUE THREAD

**Issue by itiu** [karpovr/veda#9]
сделать возможность удобного просмотра входящих и исходящих переменных и их значений,
для Process(входящие и исходящие), WorkItem (входящие и исходящие) и для WorkOrder (исходящие).

v-wf:inVars
	rdf:type rdf:Property ;
	rdfs:label "переменные"@ru ;
	rdfs:domain v-wf:Process ;
	rdfs:domain v-wf:WorkItem ;
	rdfs:range v-wf:Variable ;
.

v-wf:outVars
	rdf:type rdf:Property ;
	rdfs:label "переменные"@ru ;
	rdfs:domain v-wf:Process ;
	rdfs:domain v-wf:WorkItem ;
	rdfs:domain v-wf:WorkOrder ;
	rdfs:range v-wf:Variable ;
.

**Comment by karpovr** [comment]
Готово.
